@startuml erd_vocab

entity "roles" as r {
  *Id : int <<generated>>
  --
  name : string
}

entity "users" as u {
  *Id : int <<generated>>
  --
  username : string
  email : string
  password : string
  role_id : int
  created_at : int
  updated_at : int
}

entity "words" as w {
  *Id : int <<generated>>
  --
  word : string
  pos_id : int
  answer_key : string
  created_at : int
}

entity "pos" as p {
  *Id : int <<generated>>
  --
  desc : string
  alias : string
  created_at : int
}

entity "sentences" as s {
  *Id : int <<generated>>
  --
  created_at : int
}

entity "sentences_detail" as sd {
  word_id : int
  sentence_id : int
  --
  sentence : string
  image_url : string
  created_at : int
  updated_at : int
}

' entity "words_acc" as wac {
'   *Id : int <<generated>>
'   --
'   word_id : string
'   user_id : string 
' }

entity "words_add" as wad {
  *Id : int <<generated>>
  --
  word : string
  pos_id : int
  answer_key : string
  created_at : int
}

entity "daily_acc" as da {
  *id : int <<generated>>
  --
  total : int
  user_id : int
  created_at : int
  updated_at : int
}

r ||--|{ u
w ||--|{ sd
s ||--|{ sd
wad ||--|{ sd
p ||--|{ w
p ||--|{ wad
u ||--|| da
' u ||--|{ wac
' w ||--|{ wac
' wad ||--|{ wac

@enduml
